spring.application.name=BootMVC_P08-RequestParamBinding

#view resolver confg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


#Embeded sever port
server.port=4041

#context path for web application
server.servlet.context-path=/MVC/proj08App


